/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(if_stream_decode.h) */
/* BINDTOOL_HEADER_FILE_HASH(b7ffbaad73fe09e7fc613d84c9e4b094) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/eb200/if_stream_decode.h>
// pydoc.h is automatically generated in the build directory
#include <if_stream_decode_pydoc.h>

void bind_if_stream_decode(py::module &m) {

  using if_stream_decode = gr::eb200::if_stream_decode;

  py::class_<if_stream_decode, gr::block, gr::basic_block,
             std::shared_ptr<if_stream_decode>>(m, "if_stream_decode",
                                                D(if_stream_decode))

      .def(py::init(&if_stream_decode::make), py::arg("debug") = false,
           D(if_stream_decode, make))

      ;
}
